name: CI
"on":
  workflow_dispatch: {}
  pull_request: null
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0 "

jobs:
  install_dependencies:
    name: Install Dependencies
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3

  lint:
    name: Lint
    needs:
      - install_dependencies
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        path:
          - ./ember-statechart-component
          - ./test-app
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: cd ${{ matrix.path }} && pnpm run lint

  tests:
    name: Default Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm --filter test-app run test:ember

  floating-deps-tests:
    name: Floating Deps Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          args: '--no-lockfile'
      - run: pnpm --filter test-app run test:ember

  try-scenarios:
    name: ${{ matrix.ember-try-scenario }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs:
      - tests
    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-5.1
          - ember-5.4
          - ember-5.8
          - ember-5.12
          - ember-release
          - ember-beta
          - ember-canary
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - name: test
        working-directory: ./test-app
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }}
          --skip-cleanup

  typescript-compatibility:
    name: ${{ matrix.typescript-scenario }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - build
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@5.0
          - typescript@5.1
          - typescript@5.2
          - typescript@5.3
          - typescript@5.4
          - typescript@5.5
          - typescript@5.6
    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v3
      - name: Update TS Version
        run: pnpm add --save-dev ${{ matrix.typescript-scenario }}
        working-directory: ./test-app
      - name: Type checking
        run: >-
          pnpm --filter test-app exec tsc -v;
          pnpm --filter test-app exec glint --version;
          pnpm --filter test-app exec glint
